define("viewmodels/artistsDirectory.model", ['viewmodels/datacontext'], function (datacontext) {

    var privMethods = { };
    privMethods.isLoading = ko.observable(true),
    privMethods.artistsCollection = ko.observableArray(),
    privMethods.selectedArtist = new artist(),
    privMethods.clear = function () {
        privMethods.artistsCollection.removeAll();
    },
    privMethods.artistDTOInitializer = function (artist) {
        artist.toDelete = ko.observable(false);
        artist.FullImageUrl = ko.computed(function () {
            return 'App.WebApp/Images/Artist/' + artist.ImageUrl();
        }, artist);
    },
    privMethods.createArtistModel = function (breezeStore) {
        breezeStore.addEntityType({
            shortName: "ArtistDTO",
            namespace: "App.Domain.ValueObjects.DTO",
            autoGeneratedKeyType: AutoGeneratedKeyType.Identity,
            dataProperties: {
                Id: { dataType: DataType.Int32, isNullable: false, isPartOfKey: true },
                Name: {
                    dataType: DataType.String, maxLength: 100, isNullable: false,
                    validators: [Validator.required(), Validator.maxLength({ maxLength: 10 })]
                },
                ImageUrl: { dataType: DataType.String, isNullable: false },
            },
        });
        breezeStore.registerEntityTypeCtor("ArtistDTO", null, privMethods.artistDTOInitializer);
    };
    

    // Extract Breeze metadata definition types
    var DataType = breeze.DataType;
    var EntityType = breeze.EntityType;
    var DataProperty = breeze.DataProperty;
    var NavigationProperty = breeze.NavigationProperty;
    var AutoGeneratedKeyType = breeze.AutoGeneratedKeyType;
    var Validator = breeze.Validator;

    // The empty metadataStore to which we add types
    var store = datacontext.artistsMetadataStore;
    privMethods.createArtistModel(store);

    return {
        isLoading: privMethods.isLoading,
        artistsCollection: privMethods.artistsCollection,
        selectedArtist: privMethods.selectedArtist,
        clear: privMethods.clear,
        artistNew: privMethods.artistNew
    };
});


function artistNew(data) {
    var self = this;
    ko.mapping.fromJS(data, {}, self);
    self.toDelete = ko.observable(false);
    self.FullImageUrl = ko.computed(function () {
        return 'App.WebApp/Images/Artist/' + self.ImageUrl();
    }, self);
};

function artist() {
    this.id = ko.observable();
    this.name = ko.observable();
    this.imageUrl = ko.observable();
    this.fullImageUrl = ko.computed(function () {
        return "App.WebApp/Images/Artist/" + this.imageUrl();
    }, this),
    this.getArtistDTO = function () {
        return {
            Id: this.id(),
            Name: this.name(),
            ImageUrl: this.imageUrl(),
            FullImageUrl: '',
        };
    };
};